In [3]:
import numpy as np

In [14]:
arraexa=np.array([[0,0,0],[13,1,10],[2,2,2]])
print(arraexa)

[[ 0  0  0]
 [13  1 10]
 [ 2  2  2]]


In [15]:
print(arraexa.shape)
print(arraexa.dtype)

(3, 3)
int64


In [ ]:
a=np.ones((4,5),dtype=np.float32)

In [ ]:
print(a)

In [ ]:
a=np.zeros((6,5),dtype=np.float64)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#vectorisation in NumPy
sensor_voltages=np.array([0.5,1.2,0.8,0.9])
newdata=sensor_voltages*10
print(newdata)

[ 5. 12.  8.  9.]


In [7]:
bp_readings=np.array([125,135,110,145,150])
is_high_bp=bp_readings>140

In [8]:
print(is_high_bp)

[False False False  True  True]


In [12]:
#to generate a random number 
random_obj=np.random.random((2,5))
print(random_obj)

[[0.83054495 0.71480488 0.38004226 0.84720876 0.50362227]
 [0.86232821 0.64710359 0.60792759 0.22468724 0.89447998]]


In [15]:
#indeixing and slicesing
#slicesing is similar to when you only want to use the some part of any array
#indexing is giving index (position) to the values in the array

robot_pose=np.array([10.5,23.5,9,4,23.0])
position=robot_pose[:3]
print(position)

[10.5 23.5  9. ]


In [18]:
#patients ecg signal simulating using random
ecg_signal=np.random.random((10,7))
print(ecg_signal)


[[0.62423165 0.01320666 0.14950043 0.80711777 0.72791127 0.1987521
  0.77791515]
 [0.08186247 0.95853979 0.75931433 0.18719785 0.14956656 0.62427468
  0.29428975]
 [0.21601566 0.35438124 0.06054124 0.87776405 0.99296927 0.21549053
  0.32837907]
 [0.07975262 0.99620325 0.77747472 0.25426689 0.17843583 0.41579677
  0.97835239]
 [0.46676075 0.50127823 0.61347209 0.30187244 0.58588547 0.46940504
  0.9700997 ]
 [0.64221992 0.97360966 0.51540158 0.68627005 0.23127918 0.02660349
  0.41387968]
 [0.18819188 0.68289497 0.08027054 0.30192054 0.70932305 0.22135324
  0.98391304]
 [0.00899694 0.5246235  0.11975484 0.23053269 0.22373506 0.81268693
  0.84024434]
 [0.85835441 0.67066148 0.02419973 0.12290911 0.6436687  0.5078436
  0.97010921]
 [0.86046438 0.86538811 0.95551016 0.97565752 0.29427925 0.60481353
  0.78228719]]


In [20]:
clean_signal=[ecg_signal<0.5]
print(clean_signal)

[array([[False,  True,  True, False, False,  True, False],
       [ True, False, False,  True,  True, False,  True],
       [ True,  True,  True, False, False,  True,  True],
       [ True, False, False,  True,  True,  True, False],
       [ True, False, False,  True, False,  True, False],
       [False, False, False, False,  True,  True,  True],
       [ True, False,  True,  True, False,  True, False],
       [ True, False,  True,  True,  True, False, False],
       [False, False,  True,  True, False, False, False],
       [False, False, False, False,  True, False, False]])]
